# Generated by Django 2.2.7 on 2024-05-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'Service', 'verbose_name_plural': 'Types of service'},
        ),
    ]
